spring:
   main:
       allow-bean-definition-overriding: true
   profiles:
      active: local
   application:
      name: university-management
   jpa:
      hibernate:
         ddl-auto: none
         naming: 
           physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate-ddl: true
      properties:
         hibernate:
            show_sql: true
            dialect: org.hibernate.dialect.Oracle10gDialect
            jdbc:
               lob:
                  non_contextual_creation: true
   datasource:
      url: jdbc:oracle:thin:@localhost:1529:xe
      username: dev_user
      password: 1234
        
# --- server
server:
  port: 8997

# --- management
management:
   endpoints:
      web:
         exposure:
            include:
            - '*'
  
# --- keycloak
keycloak:
  use-resource-role-mappings: true
  credentials:
    secret: 158da796-ac58-44aa-8450-35469dec4f96
  auth-server-url: http://localhost:8089/auth/
  realm: esprit-realm
  resource: university-api
  bearer-only: true
  principal-attribute: preferred_username

application:
   migration:
     url: http://localhost:8998/
     
# --- front info
info: 
   environment:
      production: false
      env: local
      keycloak: 
         url: http://localhost:8089/auth/
         realm: esprit-realm
         clientId: university-web
      serviceBaseUrl: http://localhost:8997/
      serviceBaseUrlMigration: http://localhost:8998/
  